INSERT INTO nominees (code, id, name, category, metadata, votes, image, description, vote_target) VALUES
(UUID(), 'POTY-1000', 'BISHOP BENSON KAMAU', 'Philanthropist of the Year (Male)', '{}', 0, NULL, 'Nominee for Philanthropist  (Male)', 10000),
(UUID(), 'POTY-1001', 'ERICK OMONDI', 'Philanthropist of the Year (Male)', '{}', 0, NULL, 'Nominee for Philanthropist  (Male)', 10000),
(UUID(), 'POTY-1002', 'JEREMY DAMARIES', 'Philanthropist of the Year (Male)', '{}', 0, NULL, 'Nominee for Philanthropist  (Male)', 10000),
(UUID(), 'POTY-1003', 'KENNEDY ODEDE/ SHOFCO', 'Philanthropist of the Year (Male)', '{}', 0, NULL, 'Nominee for Philanthropist  (Male)', 10000),
(UUID(), 'POTY-1004', 'DAN WEMA', 'Philanthropist of the Year (Male)', '{}', 0, NULL, 'Nominee for Philanthropist  (Male)', 10000),
(UUID(), 'POTY-1005', 'MOSES MWENDA', 'Philanthropist of the Year (Male)', '{}', 0, NULL, 'Nominee for Philanthropist  (Male)', 10000),
(UUID(), 'POTY-1006', 'NDUGU NYORO', 'Philanthropist of the Year (Male)', '{}', 0, NULL, 'Nominee for Philanthropist  (Male)', 10000),
(UUID(), 'POTY-1007', 'GLADYS MUTHONI KIRUMBA', 'Philanthropist of the Year (Female)', '{}', 0, NULL, 'Nominee for Philanthropist  (Female)', 10000),
(UUID(), 'POTY-1008', 'DOREA CHEGE', 'Philanthropist of the Year (Female)', '{}', 0, NULL, 'Nominee for Philanthropist  (Female)', 10000),
(UUID(), 'POTY-1009', 'AKOTHEE', 'Philanthropist of the Year (Female)', '{}', 0, NULL, 'Nominee for Philanthropist  (Female)', 10000),
(UUID(), 'POTY-1010', 'ANITA SOINA', 'Philanthropist of the Year (Female)', '{}', 0, NULL, 'Nominee for Philanthropist  (Female)', 10000),
(UUID(), 'POTY-1011', 'KAIRETU JENNY', 'Philanthropist of the Year (Female)', '{}', 0, NULL, 'Nominee for Philanthropist  (Female)', 10000),
(UUID(), 'POTY-1012', 'VIVIAN ONANO', 'Philanthropist of the Year (Female)', '{}', 0, NULL, 'Nominee for Philanthropist  (Female)', 10000),
(UUID(), 'POTY-1013', 'MASSAWE JAPANNI', 'Philanthropist of the Year (Female)', '{}', 0, NULL, 'Nominee for Philanthropist  (Female)', 10000),
(UUID(), 'BAOT-1000', 'ERIC OMONDI/NJUGUSH/MUTHEE NDEGENYE/CEO BRUCE/GITHUA MANI', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Male)', 10000),
(UUID(), 'BAOT-1001', 'MBOTE NJOGU', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Male)', 10000),
(UUID(), 'BAOT-1002', 'ALFRED KOECH –SERGENT', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Male)', 10000),
(UUID(), 'BAOT-1003', 'JAY KAHIU', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Male)', 10000),
(UUID(), 'BAOT-1004', 'ROY KANYI', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Male)', 10000),
(UUID(), 'BAOT-1005', 'ELIUD KIPCHOGE', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Male)', 10000),
(UUID(), 'BAOT-1006', 'OMANYALA', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Male)', 10000),
(UUID(), 'BAOT-1007', 'KAGWE MUNGAI', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Male)', 10000),
(UUID(), 'BAOT-1008', 'BRADLEY THE GENZ', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Male)', 10000),
(UUID(), 'BAOT-1009', 'DJ DIBUL', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Male)', 10000),
(UUID(), 'BAOT-1010', 'BAHATI', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Male)', 10000),
(UUID(), 'BAOT-1011', 'TOM DAKTARI', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Male)', 10000),
(UUID(), 'BAOT-1012', 'BABA TALISHA', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Male)', 10000),
(UUID(), 'BAOT-1013', 'KABUGI', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Male)', 10000),
(UUID(), 'BAOT-1014', 'NJUGUSH', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Male)', 10000),
(UUID(), 'BAOT-1015', 'MUTHEE NDEGENYE', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Male)', 10000),
(UUID(), 'BAOT-1016', 'CEO BRUCE', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Male)', 10000),
(UUID(), 'BAOT-1017', 'GITHUA MANI', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Male)', 10000),
(UUID(), 'BAOT-1018', 'GODANA WAKO (PRINCE CHAALA)', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Male)', 10000),
(UUID(), 'BAOT-1019', 'COBRA AMBUCHI', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Male)', 10000),
(UUID(), 'BAOT-1020', 'CAROL RADULL', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Female)', 10000),
(UUID(), 'BAOT-1021', 'GLADYS MUTHONI WAKIRUMBA', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Female)', 10000),
(UUID(), 'BAOT-1022', 'AWINJA NYAMWALO', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Female)', 10000),
(UUID(), 'BAOT-1023', 'DIANA BAHATI', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Female)', 10000),
(UUID(), 'BAOT-1024', 'SARAH HASSAN', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Female)', 10000),
(UUID(), 'BAOT-1025', 'NADIA MUKAMI', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Female)', 10000),
(UUID(), 'BAOT-1026', 'It''s MORIN', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Female)', 10000),
(UUID(), 'BAOT-1027', 'CELESTINE NDINDA', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Female)', 10000),
(UUID(), 'BAOT-1028', 'SHERYL GABRIELLA', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Female)', 10000),
(UUID(), 'BAOT-1029', 'MAMITO', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Female)', 10000),
(UUID(), 'BAOT-1030', 'VICKY BRILLIANCE', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Female)', 10000),
(UUID(), 'BAOT-1031', 'NAOMI KURIA', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Female)', 10000),
(UUID(), 'BAOT-1032', 'JANTEX JEROP', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador  (Female)', 10000),
(UUID(), 'BOTY-1000', 'ALINUR MOHAMED', 'Blogger of the Year (Male)', '{}', 0, NULL, 'Nominee for Blogger  (Male)', 10000),
(UUID(), 'BOTY-1001', 'DERRIC MBUGUA', 'Blogger of the Year (Male)', '{}', 0, NULL, 'Nominee for Blogger  (Male)', 10000),
(UUID(), 'BOTY-1002', 'CYPRIAN IS, NYAKUNDI', 'Blogger of the Year (Male)', '{}', 0, NULL, 'Nominee for Blogger  (Male)', 10000),
(UUID(), 'BOTY-1003', 'NEYIOLO LIVE', 'Blogger of the Year (Male)', '{}', 0, NULL, 'Nominee for Blogger  (Male)', 10000),
(UUID(), 'BOTY-1004', 'MOSEAX', 'Blogger of the Year (Male)', '{}', 0, NULL, 'Nominee for Blogger  (Male)', 10000),
(UUID(), 'CCOT-1000', 'MCA TRICKY', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator  (Male)', 10000),
(UUID(), 'CCOT-1001', 'CRAZY KENNAR', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator  (Male)', 10000),
(UUID(), 'CCOT-1002', 'ARAP URIA', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator  (Male)', 10000),
(UUID(), 'CCOT-1003', 'KUFAI', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator  (Male)', 10000),
(UUID(), 'CCOT-1004', 'DADA SARA', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator  (Male)', 10000),
(UUID(), 'CCOT-1005', 'YY COMEDIAN', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator  (Male)', 10000),
(UUID(), 'CCOT-1006', 'EDDIE BUTITA', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator  (Male)', 10000),
(UUID(), 'CCOT-1007', 'FLAQO', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator  (Male)', 10000),
(UUID(), 'CCOT-1008', 'TERENCE CREATIVE', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator  (Male)', 10000),
(UUID(), 'CCOT-1009', 'BARUTHI WA THAYU', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator  (Male)', 10000),
(UUID(), 'CCOT-1010', 'PROPESA', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator  (Male)', 10000),
(UUID(), 'CCOT-1011', 'TAJIRIMTOTO', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator  (Male)', 10000),
(UUID(), 'CCOT-1012', 'VINNIE BAITE', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator  (Male)', 10000),
(UUID(), 'CCOT-1013', 'KADONG MWANGI COMEDIAN', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator  (Male)', 10000),
(UUID(), 'CCOT-1014', 'MR. MBILIMBILI', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator  (Male)', 10000),
(UUID(), 'CCOT-1015', 'KINUTHIA WANYU RII (HARRISLON K MBURU)', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator  (Male)', 10000),
(UUID(), 'CCOT-1016', 'CEO BRUCE', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator  (Male)', 10000),
(UUID(), 'CCOT-1017', 'GOGO SMALL', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator  (Male)', 10000),
(UUID(), 'CCOT-1018', 'SENGE HELLENA', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator  (Male)', 10000),
(UUID(), 'CCOT-1019', 'MOJEJE KIAZALA', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator  (Male)', 10000),
(UUID(), 'CCOT-1020', 'USEFULIDIOTY', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator  (Male)', 10000),
(UUID(), 'CCOT-1021', 'SMILE PRINCE', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator  (Male)', 10000),
(UUID(), 'CCOT-1022', 'MORIN ACTRESS', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator  (Female)', 10000),
(UUID(), 'CCOT-1023', 'AUNTIE JEMIMAH', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator  (Female)', 10000),
(UUID(), 'CCOT-1024', 'DEM WA FB', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator  (Female)', 10000),
(UUID(), 'CCOT-1025', 'HUSNA ROSE', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator  (Female)', 10000),
(UUID(), 'CCOT-1026', 'VELMA ADALA', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator  (Female)', 10000),
(UUID(), 'CCOT-1027', 'JACKIE MATUBIA', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator  (Female)', 10000),
(UUID(), 'CCOT-1028', 'DIANA BAHATI', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator  (Female)', 10000),
(UUID(), 'CCOT-1029', 'AZZIAD NASENYA', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator  (Female)', 10000),
(UUID(), 'CCOT-1030', 'TESS MWAURA', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator  (Female)', 10000),
(UUID(), 'CCOT-1031', 'MISS TRUDY', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator  (Female)', 10000),
(UUID(), 'CCOT-1032', 'LYNNE NGUGI', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator  (Female)', 10000),
(UUID(), 'CCOT-1033', 'MUNGAI EVE', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator  (Female)', 10000),
(UUID(), 'CCOT-1034', 'DIANA DAISY –GAU', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator  (Female)', 10000),
(UUID(), 'CCOT-1035', 'MAURINE KABU', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator  (Female)', 10000),
(UUID(), 'CCOT-1036', 'VELMA ADALA', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator  (Female)', 10000),
(UUID(), 'CCOT-1037', 'MITCHELLE MJAKA MFINE', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator  (Female)', 10000),
(UUID(), 'CCOT-1038', 'SHARNIZE ACTRESS', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator  (Female)', 10000),
(UUID(), 'CCOT-1039', 'JUST SALET', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator  (Female)', 10000),
(UUID(), 'CCOT-1040', 'ANGEL ATIENO', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator  (Female)', 10000),
(UUID(), 'EOTY-1000', 'KENJAVA WAKAGOTO', 'Entrepreneur of the Year (Male)', '{}', 0, NULL, 'Nominee for Entrepreneur  (Male)', 10000),
(UUID(), 'EOTY-1001', 'PREZZO LOGISTIC MOULDINGS', 'Entrepreneur of the Year (Male)', '{}', 0, NULL, 'Nominee for Entrepreneur  (Male)', 10000),
(UUID(), 'EOTY-1002', 'MURAGE MODERN PACIFIC FANITURE', 'Entrepreneur of the Year (Male)', '{}', 0, NULL, 'Nominee for Entrepreneur  (Male)', 10000),
(UUID(), 'EOTY-1003', 'MARIDADY MOTORS LTD', 'Entrepreneur of the Year (Male)', '{}', 0, NULL, 'Nominee for Entrepreneur  (Male)', 10000),
(UUID(), 'EOTY-1004', 'MOFARM JM', 'Entrepreneur of the Year (Male)', '{}', 0, NULL, 'Nominee for Entrepreneur  (Male)', 10000),
(UUID(), 'EOTY-1005', 'MWENDA THURANIRA (MAMBO FRESH)', 'Entrepreneur of the Year (Male)', '{}', 0, NULL, 'Nominee for Entrepreneur  (Male)', 10000),
(UUID(), 'EOTY-1006', 'BARUTHI WA THAYU', 'Entrepreneur of the Year (Male)', '{}', 0, NULL, 'Nominee for Entrepreneur  (Male)', 10000),
(UUID(), 'EOTY-1007', 'DAMARIS WA DAMA SPARES', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur  (Female)', 10000),
(UUID(), 'EOTY-1008', 'CATHERINE WAMBUGU (WAMBUGU APPLES)', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur  (Female)', 10000),
(UUID(), 'EOTY-1009', 'SHIKUH HI-STYLE', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur  (Female)', 10000),
(UUID(), 'EOTY-1010', 'BETTY HAMISHA (MUTHONI)', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur  (Female)', 10000),
(UUID(), 'EOTY-1011', 'ESTHER MUCHEMI', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur  (Female)', 10000),
(UUID(), 'EOTY-1012', 'NANA OWITI', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur  (Female)', 10000),
(UUID(), 'EOTY-1013', 'LIZ NJUGUNA', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur  (Female)', 10000),
(UUID(), 'EOTY-1014', 'AMELINA ACHIENG', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur  (Female)', 10000),
(UUID(), 'EOTY-1015', 'ANERLISA MUIGAI', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur  (Female)', 10000),
(UUID(), 'EOTY-1016', 'HILDA MORAA', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur  (Female)', 10000),
(UUID(), 'EOTY-1017', 'NAISIAE NAAADOKILA', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur  (Female)', 10000),
(UUID(), 'EOTY-1018', 'CAROLE KINOTI', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur  (Female)', 10000),
(UUID(), 'EOTY-1019', 'NJERI RIONGE', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur  (Female)', 10000),
(UUID(), 'EOTY-1020', 'WINJOY KANANU', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur  (Female)', 10000),
(UUID(), 'EOTY-1021', 'Hon. ANNASTACIA MUTHINI MUENDOMA', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur  (Female)', 10000),
(UUID(), 'EOTY-1022', 'ESTHER WAKIMANITV NDUKU', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur  (Female)', 10000),
(UUID(), 'EOTY-1023', 'MAURINE KABU', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur  (Female)', 10000),
(UUID(), 'EOTY-1024', 'NANA OWITI', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur  (Female)', 10000),
(UUID(), 'YLOT-1000', 'HON. BABU OWINO', 'Youth Leader of the Year (Male)', '{}', 0, NULL, 'Nominee for Youth Leader  (Male)', 10000),
(UUID(), 'YLOT-1001', 'HON.  JALANGO', 'Youth Leader of the Year (Male)', '{}', 0, NULL, 'Nominee for Youth Leader  (Male)', 10000),
(UUID(), 'YLOT-1002', 'HON. NDINDI NYORO', 'Youth Leader of the Year (Male)', '{}', 0, NULL, 'Nominee for Youth Leader  (Male)', 10000),
(UUID(), 'YLOT-1003', 'HON. JOHN METHU', 'Youth Leader of the Year (Male)', '{}', 0, NULL, 'Nominee for Youth Leader  (Male)', 10000),
(UUID(), 'YLOT-1004', 'HON. JOHN PAUL MWIRIGI', 'Youth Leader of the Year (Male)', '{}', 0, NULL, 'Nominee for Youth Leader  (Male)', 10000),
(UUID(), 'YLOT-1005', 'MWANGI MUCHIRI', 'Youth Leader of the Year (Male)', '{}', 0, NULL, 'Nominee for Youth Leader  (Male)', 10000),
(UUID(), 'YLOT-1006', 'HON. PETER KALERWA SALASYA', 'Youth Leader of the Year (Male)', '{}', 0, NULL, 'Nominee for Youth Leader  (Male)', 10000),
(UUID(), 'YLOT-1007', 'Hon. JALANGO', 'Youth Leader of the Year (Male)', '{}', 0, NULL, 'Nominee for Youth Leader  (Male)', 10000),
(UUID(), 'YLOT-1008', 'FIKIRINI JACOBS', 'Youth Leader of the Year (Male)', '{}', 0, NULL, 'Nominee for Youth Leader  (Male)', 10000),
(UUID(), 'YLOT-1009', 'STEPHEN LETOO', 'Youth Leader of the Year (Male)', '{}', 0, NULL, 'Nominee for Youth Leader  (Male)', 10000),
(UUID(), 'YLOT-1010', 'HON. NJERI MAINA', 'Youth Leader of the Year (Female)', '{}', 0, NULL, 'Nominee for Youth Leader  (Female)', 10000),
(UUID(), 'YLOT-1011', 'HON. MBITHE MULINGE', 'Youth Leader of the Year (Female)', '{}', 0, NULL, 'Nominee for Youth Leader  (Female)', 10000),
(UUID(), 'YLOT-1012', 'HON. CYNTHIA MUGE', 'Youth Leader of the Year (Female)', '{}', 0, NULL, 'Nominee for Youth Leader  (Female)', 10000),
(UUID(), 'YLOT-1013', 'HON. LINET TOTO', 'Youth Leader of the Year (Female)', '{}', 0, NULL, 'Nominee for Youth Leader  (Female)', 10000),
(UUID(), 'YLOT-1014', 'HON. ESTHER OKENYURI', 'Youth Leader of the Year (Female)', '{}', 0, NULL, 'Nominee for Youth Leader  (Female)', 10000),
(UUID(), 'YLOT-1015', 'KAREN NYAMU', 'Youth Leader of the Year (Female)', '{}', 0, NULL, 'Nominee for Youth Leader  (Female)', 10000),
(UUID(), 'IOTY-1000', 'SIR BONNIE BRANDS', 'Innovator of the Year (Male)', '{}', 0, NULL, 'Nominee for Innovator  (Male)', 10000),
(UUID(), 'IOTY-1001', 'MURAGE MORDERN PACIFIC', 'Innovator of the Year (Male)', '{}', 0, NULL, 'Nominee for Innovator  (Male)', 10000),
(UUID(), 'IOTY-1002', 'BROBOX', 'Innovator of the Year (Male)', '{}', 0, NULL, 'Nominee for Innovator  (Male)', 10000),
(UUID(), 'IOTY-1003', 'MC KAJIM', 'Innovator of the Year (Male)', '{}', 0, NULL, 'Nominee for Innovator  (Male)', 10000),
(UUID(), 'IOTY-1004', 'HAMO THE PROFESSOR', 'Innovator of the Year (Male)', '{}', 0, NULL, 'Nominee for Innovator  (Male)', 10000),
(UUID(), 'IOTY-1005', 'TR_KALAUSI', 'Innovator of the Year (Male)', '{}', 0, NULL, 'Nominee for Innovator  (Male)', 10000),
(UUID(), 'IOTY-1006', 'SIMON PLUMBING', 'Innovator of the Year (Male)', '{}', 0, NULL, 'Nominee for Innovator  (Male)', 10000),
(UUID(), 'IOTY-1007', 'KHOJA AFRIQUE (MUSANII)', 'Innovator of the Year (Male)', '{}', 0, NULL, 'Nominee for Innovator  (Male)', 10000),
(UUID(), 'IOTY-1008', 'DAN WEMA', 'Innovator of the Year (Male)', '{}', 0, NULL, 'Nominee for Innovator  (Male)', 10000),
(UUID(), 'IOTY-1009', 'ELVIS W', 'Innovator of the Year (Male)', '{}', 0, NULL, 'Nominee for Innovator  (Male)', 10000),
(UUID(), 'IOTY-1010', 'KELLY INSPIRATION', 'Innovator of the Year (Male)', '{}', 0, NULL, 'Nominee for Innovator  (Male)', 10000),
(UUID(), 'IOTY-1011', 'PRESENTOR KAI', 'Innovator of the Year (Male)', '{}', 0, NULL, 'Nominee for Innovator  (Male)', 10000),
(UUID(), 'IOTY-1012', 'KELSY KERUBO', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator  (Female)', 10000),
(UUID(), 'IOTY-1013', 'EV MERCY NUNGARI', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator  (Female)', 10000),
(UUID(), 'IOTY-1014', 'MERCY MAINA OFFICIAL', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator  (Female)', 10000),
(UUID(), 'IOTY-1015', 'WANGECI WA KARIUKI', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator  (Female)', 10000),
(UUID(), 'IOTY-1016', 'LUCIANA CREATIVE', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator  (Female)', 10000),
(UUID(), 'IOTY-1017', 'NKATHA OFFICIAL', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator  (Female)', 10000),
(UUID(), 'IOTY-1018', 'ANN GATIBA', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator  (Female)', 10000),
(UUID(), 'IOTY-1019', 'NJERI WA MUIGAI NJOROGE', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator  (Female)', 10000),
(UUID(), 'IOTY-1020', 'WAIRIMU KIMANI', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator  (Female)', 10000),
(UUID(), 'IOTY-1021', 'NAISIAE NAADOKILA', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator  (Female)', 10000),
(UUID(), 'IOTY-1022', 'TRISHA KHALID', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator  (Female)', 10000),
(UUID(), 'IOTY-1023', 'CHELAA VALLEYGIRL', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator  (Female)', 10000),
(UUID(), 'IOTY-1024', 'BETTY BAYO', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator  (Female)', 10000),
(UUID(), 'IOTY-1025', 'STACY WA DIGITAL', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator  (Female)', 10000),
(UUID(), 'IOTY-1026', 'CAROL KATRUE', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator  (Female)', 10000),
(UUID(), 'IOTY-1027', 'MAURINE KABU', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator  (Female)', 10000),
(UUID(), 'IOTY-1028', 'DIANA YEGON', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator  (Female)', 10000),
(UUID(), 'C-1000', 'MC-GOGO', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian  (male)', 10000),
(UUID(), 'C-1001', 'SENGE HELLENA', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian  (male)', 10000),
(UUID(), 'C-1002', 'GOGO SMALL', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian  (male)', 10000),
(UUID(), 'C-1003', 'SAMMY KIOKO COMEDIAN', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian  (male)', 10000),
(UUID(), 'C-1004', 'JAYMO DECIN', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian  (male)', 10000),
(UUID(), 'C-1005', 'MOJEJE KIAZALA', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian  (male)', 10000),
(UUID(), 'C-1006', 'KAFENGO', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian  (male)', 10000),
(UUID(), 'C-1007', 'WILSON MACHARIA', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian  (male)', 10000),
(UUID(), 'C-1008', 'NGANO COMEDIAN', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian  (male)', 10000),
(UUID(), 'C-1009', 'NYONJORO', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian  (male)', 10000),
(UUID(), 'C-1010', 'MURIFE', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian  (male)', 10000),
(UUID(), 'C-1011', 'FLAQO', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian  (male)', 10000),
(UUID(), 'C-1012', 'GIKONYORE', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian  (male)', 10000),
(UUID(), 'C-1013', 'VINNIE BAITE', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian  (male)', 10000),
(UUID(), 'C-1014', 'NASRA', 'Comedian of the year (female)', '{}', 0, NULL, 'Nominee for Comedian  (female)', 10000),
(UUID(), 'C-1015', 'JEMUTAI', 'Comedian of the year (female)', '{}', 0, NULL, 'Nominee for Comedian  (female)', 10000),
(UUID(), 'C-1016', 'WANJIRU CLAIRE FUNS', 'Comedian of the year (female)', '{}', 0, NULL, 'Nominee for Comedian  (female)', 10000),
(UUID(), 'C-1017', 'MAMITO EUNICE', 'Comedian of the year (female)', '{}', 0, NULL, 'Nominee for Comedian  (female)', 10000),
(UUID(), 'C-1018', 'WAJOY', 'Comedian of the year (female)', '{}', 0, NULL, 'Nominee for Comedian  (female)', 10000),
(UUID(), 'C-1019', 'AUNTIE JEMIMAH', 'Comedian of the year (female)', '{}', 0, NULL, 'Nominee for Comedian  (female)', 10000),
(UUID(), 'CCOT-1041', 'GEOFFREY MOSIRIA', 'Community Champion of the Year (Male)', '{}', 0, NULL, 'Nominee for Community Champion  (Male)', 10000),
(UUID(), 'CCOT-1042', 'FATHER KINYUA’S ONLINE', 'Community Champion of the Year (Male)', '{}', 0, NULL, 'Nominee for Community Champion  (Male)', 10000),
(UUID(), 'CCOT-1043', 'SAMMY ONDIMU NGARE', 'Community Champion of the Year (Male)', '{}', 0, NULL, 'Nominee for Community Champion  (Male)', 10000),
(UUID(), 'CCOT-1044', 'MORARA KEBASO', 'Community Champion of the Year (Male)', '{}', 0, NULL, 'Nominee for Community Champion  (Male)', 10000),
(UUID(), 'CCOT-1045', 'KURURIA TV', 'Community Champion of the Year (Male)', '{}', 0, NULL, 'Nominee for Community Champion  (Male)', 10000),
(UUID(), 'CCOT-1046', 'ELVIS W', 'Community Champion of the Year (Male)', '{}', 0, NULL, 'Nominee for Community Champion  (Male)', 10000),
(UUID(), 'CCOT-1047', 'SHIKSHA ARORA', 'Community Champion of the Year (Female)', '{}', 0, NULL, 'Nominee for Community Champion  (Female)', 10000),
(UUID(), 'CCOT-1048', 'WANJA NYARARI ROSE', 'Community Champion of the Year (Female)', '{}', 0, NULL, 'Nominee for Community Champion  (Female)', 10000),
(UUID(), 'CCOT-1049', 'REV. JOY BENSON', 'Community Champion of the Year (Female)', '{}', 0, NULL, 'Nominee for Community Champion  (Female)', 10000),
(UUID(), 'CCOT-1050', 'Tr. CILLAH', 'Community Champion of the Year (Female)', '{}', 0, NULL, 'Nominee for Community Champion  (Female)', 10000),
(UUID(), 'CCOT-1051', 'WANJIKU STEPHENS', 'Community Champion of the Year (Female)', '{}', 0, NULL, 'Nominee for Community Champion  (Female)', 10000),
(UUID(), 'CCOT-1052', 'TEACHER MARION MUKENYI', 'Community Champion of the Year (Female)', '{}', 0, NULL, 'Nominee for Community Champion  (Female)', 10000),
(UUID(), 'CCOT-1053', 'HON. SHARLEEN WAMBUI MAINA (SHAR)', 'Community Champion of the Year (Female)', '{}', 0, NULL, 'Nominee for Community Champion  (Female)', 10000),
(UUID(), 'CCOT-1054', 'KARIGITHINJI', 'Community Champion of the Year (Female)', '{}', 0, NULL, 'Nominee for Community Champion  (Female)', 10000),
(UUID(), 'CCOT-1055', 'REHEMA KITETO', 'Community Champion of the Year (Female)', '{}', 0, NULL, 'Nominee for Community Champion  (Female)', 10000),
(UUID(), 'CCOT-1056', 'DIANA DAISY –GAU', 'Community Champion of the Year (Female)', '{}', 0, NULL, 'Nominee for Community Champion  (Female)', 10000),
(UUID(), 'CCOT-1057', 'LYNN NGUGI', 'Community Champion of the Year (Female)', '{}', 0, NULL, 'Nominee for Community Champion  (Female)', 10000),
(UUID(), 'IOTY-1029', 'BABA TALISHA', 'Influencer of the Year (Male)', '{}', 0, NULL, 'Nominee for Influencer  (Male)', 10000),
(UUID(), 'IOTY-1030', 'Dr. OFWENEKE', 'Influencer of the Year (Male)', '{}', 0, NULL, 'Nominee for Influencer  (Male)', 10000),
(UUID(), 'IOTY-1031', 'OGA OBINNA', 'Influencer of the Year (Male)', '{}', 0, NULL, 'Nominee for Influencer  (Male)', 10000),
(UUID(), 'IOTY-1032', 'Tom DAKTARI', 'Influencer of the Year (Male)', '{}', 0, NULL, 'Nominee for Influencer  (Male)', 10000),
(UUID(), 'IOTY-1033', 'HAMO THE PROFFESOR', 'Influencer of the Year (Male)', '{}', 0, NULL, 'Nominee for Influencer  (Male)', 10000),
(UUID(), 'IOTY-1034', 'SANDRA DACHA', 'Influencer of the Year (Female)', '{}', 0, NULL, 'Nominee for Influencer  (Female)', 10000),
(UUID(), 'IOTY-1035', 'WANJA MWAURA', 'Influencer of the Year (Female)', '{}', 0, NULL, 'Nominee for Influencer  (Female)', 10000),
(UUID(), 'IOTY-1036', 'TRIZA MAMAKE MURAYA', 'Influencer of the Year (Female)', '{}', 0, NULL, 'Nominee for Influencer  (Female)', 10000),
(UUID(), 'IOTY-1037', 'Lulu Hassan', 'Influencer of the Year (Female)', '{}', 0, NULL, 'Nominee for Influencer  (Female)', 10000),
(UUID(), 'IOTY-1038', 'Dr. Regina King’ori CPA-K', 'Influencer of the Year (Female)', '{}', 0, NULL, 'Nominee for Influencer  (Female)', 10000),
(UUID(), 'IOTY-1039', 'NAOMI KURIA', 'Influencer of the Year (Female)', '{}', 0, NULL, 'Nominee for Influencer  (Female)', 10000),
(UUID(), 'IOTY-1040', 'ECRENE MADAGA', 'Influencer of the Year (Female)', '{}', 0, NULL, 'Nominee for Influencer  (Female)', 10000),
(UUID(), 'IOTY-1041', 'MILLY CHEBBY', 'Influencer of the Year (Female)', '{}', 0, NULL, 'Nominee for Influencer  (Female)', 10000),
(UUID(), 'D-1000', 'DJMOKENYA', 'DJ of the year (Male)', '{}', 0, NULL, 'Nominee for DJ  (Male)', 10000),
(UUID(), 'D-1001', 'DJ MACDEE TOP MC', 'DJ of the year (Male)', '{}', 0, NULL, 'Nominee for DJ  (Male)', 10000),
(UUID(), 'D-1002', 'DJ DIBUL', 'DJ of the year (Male)', '{}', 0, NULL, 'Nominee for DJ  (Male)', 10000),
(UUID(), 'DOTY-1000', 'DJ SOFIA MACHARIA', 'DJ of the Year (Female)', '{}', 0, NULL, 'Nominee for DJ  (Female)', 10000),
(UUID(), 'DOTY-1001', 'DJ NYC KENYA', 'DJ of the Year (Female)', '{}', 0, NULL, 'Nominee for DJ  (Female)', 10000),
(UUID(), 'DOTY-1002', 'DJ SONNIE M', 'DJ of the Year (Female)', '{}', 0, NULL, 'Nominee for DJ  (Female)', 10000),
(UUID(), 'DOTY-1003', 'DJ SLIM 254', 'DJ of the Year (Female)', '{}', 0, NULL, 'Nominee for DJ  (Female)', 10000),
(UUID(), 'POTY-1014', 'MC KOGI INVESTOR', 'PODCAST OF THE YEAR', '{}', 0, NULL, 'Nominee for PODCAST', 10000),
(UUID(), 'POTY-1015', 'GUKA WA NYUMBA KUMI', 'PODCAST OF THE YEAR', '{}', 0, NULL, 'Nominee for PODCAST', 10000),
(UUID(), 'POTY-1016', 'JEFF KURIA', 'PODCAST OF THE YEAR', '{}', 0, NULL, 'Nominee for PODCAST', 10000),
(UUID(), 'POTY-1017', 'PAXSON CHEGE NGUNYA', 'PODCAST OF THE YEAR', '{}', 0, NULL, 'Nominee for PODCAST', 10000),
(UUID(), 'POTY-1018', 'LYNNE NGUGI', 'PODCAST OF THE YEAR', '{}', 0, NULL, 'Nominee for PODCAST', 10000),
(UUID(), 'POTY-1019', 'MIC CHEQUE', 'PODCAST OF THE YEAR', '{}', 0, NULL, 'Nominee for PODCAST', 10000),
(UUID(), 'POTY-1020', 'THE MESSY IN BETWEEN', 'PODCAST OF THE YEAR', '{}', 0, NULL, 'Nominee for PODCAST', 10000),
(UUID(), 'POTY-1021', 'BY THE WAY', 'PODCAST OF THE YEAR', '{}', 0, NULL, 'Nominee for PODCAST', 10000),
(UUID(), 'FP-1000', 'SIKIKA ROAD SAFETY', 'Facebook pages of the year', '{}', 0, NULL, 'Nominee for Facebook pages', 10000),
(UUID(), 'FP-1001', 'TUKO.CO.KE', 'Facebook pages of the year', '{}', 0, NULL, 'Nominee for Facebook pages', 10000),
(UUID(), 'FP-1002', 'KENYANS.CO.KE', 'Facebook pages of the year', '{}', 0, NULL, 'Nominee for Facebook pages', 10000),
(UUID(), 'FP-1003', 'MWAGO WA MUGIKUYU', 'Facebook pages of the year', '{}', 0, NULL, 'Nominee for Facebook pages', 10000),
(UUID(), 'FP-1004', 'DMK MEDIA GROUP', 'Facebook pages of the year', '{}', 0, NULL, 'Nominee for Facebook pages', 10000),
(UUID(), 'FP-1005', '7 NEWS GLOBAL', 'Facebook pages of the year', '{}', 0, NULL, 'Nominee for Facebook pages', 10000),
(UUID(), 'FP-1006', 'NAIROBI GOSSIP CLUB', 'Facebook pages of the year', '{}', 0, NULL, 'Nominee for Facebook pages', 10000),
(UUID(), 'FP-1007', 'PULSE KENYA', 'Facebook pages of the year', '{}', 0, NULL, 'Nominee for Facebook pages', 10000),
(UUID(), 'FP-1008', 'MALEMA TV', 'Facebook pages of the year', '{}', 0, NULL, 'Nominee for Facebook pages', 10000);