INSERT INTO nominees (code, id, name, category, metadata, votes, image, description, vote_target) VALUES
(UUID(), 'philanthropist_of_the_year_male_1', 'BISHOP BENSON KAMAU', 'Philanthropist of the Year (Male)', '{}', 0, NULL, 'Nominee for Philanthropist of the Year (Male)', 10000),
(UUID(), 'philanthropist_of_the_year_male_2', 'ERICK OMONDI', 'Philanthropist of the Year (Male)', '{}', 0, NULL, 'Nominee for Philanthropist of the Year (Male)', 10000),
(UUID(), 'philanthropist_of_the_year_male_3', 'JEREMY DAMARIES', 'Philanthropist of the Year (Male)', '{}', 0, NULL, 'Nominee for Philanthropist of the Year (Male)', 10000),
(UUID(), 'philanthropist_of_the_year_male_4', 'KENNEDY ODEDE/ SHOFCO', 'Philanthropist of the Year (Male)', '{}', 0, NULL, 'Nominee for Philanthropist of the Year (Male)', 10000),
(UUID(), 'philanthropist_of_the_year_male_5', 'DAN WEMA', 'Philanthropist of the Year (Male)', '{}', 0, NULL, 'Nominee for Philanthropist of the Year (Male)', 10000),
(UUID(), 'philanthropist_of_the_year_male_6', 'MOSES MWENDA', 'Philanthropist of the Year (Male)', '{}', 0, NULL, 'Nominee for Philanthropist of the Year (Male)', 10000),
(UUID(), 'philanthropist_of_the_year_male_7', 'NDUGU NYORO', 'Philanthropist of the Year (Male)', '{}', 0, NULL, 'Nominee for Philanthropist of the Year (Male)', 10000),
(UUID(), 'philanthropist_of_the_year_female_8', 'GLADYS MUTHONI KIRUMBA', 'Philanthropist of the Year (Female)', '{}', 0, NULL, 'Nominee for Philanthropist of the Year (Female)', 10000),
(UUID(), 'philanthropist_of_the_year_female_9', 'DOREA CHEGE', 'Philanthropist of the Year (Female)', '{}', 0, NULL, 'Nominee for Philanthropist of the Year (Female)', 10000),
(UUID(), 'philanthropist_of_the_year_female_10', 'AKOTHEE', 'Philanthropist of the Year (Female)', '{}', 0, NULL, 'Nominee for Philanthropist of the Year (Female)', 10000),
(UUID(), 'philanthropist_of_the_year_female_11', 'ANITA SOINA', 'Philanthropist of the Year (Female)', '{}', 0, NULL, 'Nominee for Philanthropist of the Year (Female)', 10000),
(UUID(), 'philanthropist_of_the_year_female_12', 'KAIRETU JENNY', 'Philanthropist of the Year (Female)', '{}', 0, NULL, 'Nominee for Philanthropist of the Year (Female)', 10000),
(UUID(), 'philanthropist_of_the_year_female_13', 'VIVIAN ONANO', 'Philanthropist of the Year (Female)', '{}', 0, NULL, 'Nominee for Philanthropist of the Year (Female)', 10000),
(UUID(), 'philanthropist_of_the_year_female_14', 'MASSAWE JAPANNI', 'Philanthropist of the Year (Female)', '{}', 0, NULL, 'Nominee for Philanthropist of the Year (Female)', 10000),
(UUID(), 'brand_ambassador_of_the_year_male_15', 'ERIC OMONDI/NJUGUSH/MUTHEE NDEGENYE/CEO BRUCE/GITHUA MANI', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Male)', 10000),
(UUID(), 'brand_ambassador_of_the_year_male_16', 'MBOTE NJOGU', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Male)', 10000),
(UUID(), 'brand_ambassador_of_the_year_male_17', 'ALFRED KOECH –SERGENT', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Male)', 10000),
(UUID(), 'brand_ambassador_of_the_year_male_18', 'JAY KAHIU', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Male)', 10000),
(UUID(), 'brand_ambassador_of_the_year_male_19', 'ROY KANYI', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Male)', 10000),
(UUID(), 'brand_ambassador_of_the_year_male_20', 'ELIUD KIPCHOGE', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Male)', 10000),
(UUID(), 'brand_ambassador_of_the_year_male_21', 'OMANYALA', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Male)', 10000),
(UUID(), 'brand_ambassador_of_the_year_male_22', 'KAGWE MUNGAI', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Male)', 10000),
(UUID(), 'brand_ambassador_of_the_year_male_23', 'BRADLEY THE GENZ', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Male)', 10000),
(UUID(), 'brand_ambassador_of_the_year_male_24', 'DJ DIBUL', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Male)', 10000),
(UUID(), 'brand_ambassador_of_the_year_male_25', 'BAHATI', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Male)', 10000),
(UUID(), 'brand_ambassador_of_the_year_male_26', 'TOM DAKTARI', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Male)', 10000),
(UUID(), 'brand_ambassador_of_the_year_male_27', 'BABA TALISHA', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Male)', 10000),
(UUID(), 'brand_ambassador_of_the_year_male_28', 'KABUGI', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Male)', 10000),
(UUID(), 'brand_ambassador_of_the_year_male_29', 'NJUGUSH', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Male)', 10000),
(UUID(), 'brand_ambassador_of_the_year_male_30', 'MUTHEE NDEGENYE', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Male)', 10000),
(UUID(), 'brand_ambassador_of_the_year_male_31', 'CEO BRUCE', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Male)', 10000),
(UUID(), 'brand_ambassador_of_the_year_male_32', 'GITHUA MANI', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Male)', 10000),
(UUID(), 'brand_ambassador_of_the_year_male_33', 'GODANA WAKO (PRINCE CHAALA)', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Male)', 10000),
(UUID(), 'brand_ambassador_of_the_year_male_34', 'COBRA AMBUCHI', 'Brand Ambassador of the Year (Male)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Male)', 10000),
(UUID(), 'brand_ambassador_of_the_year_female_35', 'CAROL RADULL', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Female)', 10000),
(UUID(), 'brand_ambassador_of_the_year_female_36', 'GLADYS MUTHONI WAKIRUMBA', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Female)', 10000),
(UUID(), 'brand_ambassador_of_the_year_female_37', 'AWINJA NYAMWALO', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Female)', 10000),
(UUID(), 'brand_ambassador_of_the_year_female_38', 'DIANA BAHATI', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Female)', 10000),
(UUID(), 'brand_ambassador_of_the_year_female_39', 'SARAH HASSAN', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Female)', 10000),
(UUID(), 'brand_ambassador_of_the_year_female_40', 'NADIA MUKAMI', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Female)', 10000),
(UUID(), 'brand_ambassador_of_the_year_female_41', 'It''s MORIN', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Female)', 10000),
(UUID(), 'brand_ambassador_of_the_year_female_42', 'CELESTINE NDINDA', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Female)', 10000),
(UUID(), 'brand_ambassador_of_the_year_female_43', 'SHERYL GABRIELLA', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Female)', 10000),
(UUID(), 'brand_ambassador_of_the_year_female_44', 'MAMITO', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Female)', 10000),
(UUID(), 'brand_ambassador_of_the_year_female_45', 'VICKY BRILLIANCE', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Female)', 10000),
(UUID(), 'brand_ambassador_of_the_year_female_46', 'NAOMI KURIA', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Female)', 10000),
(UUID(), 'brand_ambassador_of_the_year_female_47', 'JANTEX JEROP', 'Brand Ambassador of the Year (Female)', '{}', 0, NULL, 'Nominee for Brand Ambassador of the Year (Female)', 10000),
(UUID(), 'blogger_of_the_year_male_48', 'ALINUR MOHAMED', 'Blogger of the Year (Male)', '{}', 0, NULL, 'Nominee for Blogger of the Year (Male)', 10000),
(UUID(), 'blogger_of_the_year_male_49', 'DERRIC MBUGUA', 'Blogger of the Year (Male)', '{}', 0, NULL, 'Nominee for Blogger of the Year (Male)', 10000),
(UUID(), 'blogger_of_the_year_male_50', 'CYPRIAN IS, NYAKUNDI', 'Blogger of the Year (Male)', '{}', 0, NULL, 'Nominee for Blogger of the Year (Male)', 10000),
(UUID(), 'blogger_of_the_year_male_51', 'NEYIOLO LIVE', 'Blogger of the Year (Male)', '{}', 0, NULL, 'Nominee for Blogger of the Year (Male)', 10000),
(UUID(), 'blogger_of_the_year_male_52', 'MOSEAX', 'Blogger of the Year (Male)', '{}', 0, NULL, 'Nominee for Blogger of the Year (Male)', 10000),
(UUID(), 'content_creator_of_the_year_male_53', 'MCA TRICKY', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Male)', 10000),
(UUID(), 'content_creator_of_the_year_male_54', 'CRAZY KENNAR', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Male)', 10000),
(UUID(), 'content_creator_of_the_year_male_55', 'ARAP URIA', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Male)', 10000),
(UUID(), 'content_creator_of_the_year_male_56', 'KUFAI', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Male)', 10000),
(UUID(), 'content_creator_of_the_year_male_57', 'DADA SARA', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Male)', 10000),
(UUID(), 'content_creator_of_the_year_male_58', 'YY COMEDIAN', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Male)', 10000),
(UUID(), 'content_creator_of_the_year_male_59', 'EDDIE BUTITA', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Male)', 10000),
(UUID(), 'content_creator_of_the_year_male_60', 'FLAQO', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Male)', 10000),
(UUID(), 'content_creator_of_the_year_male_61', 'TERENCE CREATIVE', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Male)', 10000),
(UUID(), 'content_creator_of_the_year_male_62', 'BARUTHI WA THAYU', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Male)', 10000),
(UUID(), 'content_creator_of_the_year_male_63', 'PROPESA', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Male)', 10000),
(UUID(), 'content_creator_of_the_year_male_64', 'TAJIRIMTOTO', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Male)', 10000),
(UUID(), 'content_creator_of_the_year_male_65', 'VINNIE BAITE', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Male)', 10000),
(UUID(), 'content_creator_of_the_year_male_66', 'KADONG MWANGI COMEDIAN', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Male)', 10000),
(UUID(), 'content_creator_of_the_year_male_67', 'MR. MBILIMBILI', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Male)', 10000),
(UUID(), 'content_creator_of_the_year_male_68', 'KINUTHIA WANYU RII (HARRISLON K MBURU)', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Male)', 10000),
(UUID(), 'content_creator_of_the_year_male_69', 'CEO BRUCE', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Male)', 10000),
(UUID(), 'content_creator_of_the_year_male_70', 'GOGO SMALL', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Male)', 10000),
(UUID(), 'content_creator_of_the_year_male_71', 'SENGE HELLENA', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Male)', 10000),
(UUID(), 'content_creator_of_the_year_male_72', 'MOJEJE KIAZALA', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Male)', 10000),
(UUID(), 'content_creator_of_the_year_male_73', 'USEFULIDIOTY', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Male)', 10000),
(UUID(), 'content_creator_of_the_year_male_74', 'SMILE PRINCE', 'Content Creator of the Year (Male)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Male)', 10000),
(UUID(), 'content_creator_of_the_year_female_75', 'MORIN ACTRESS', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Female)', 10000),
(UUID(), 'content_creator_of_the_year_female_76', 'AUNTIE JEMIMAH', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Female)', 10000),
(UUID(), 'content_creator_of_the_year_female_77', 'DEM WA FB', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Female)', 10000),
(UUID(), 'content_creator_of_the_year_female_78', 'HUSNA ROSE', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Female)', 10000),
(UUID(), 'content_creator_of_the_year_female_79', 'VELMA ADALA', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Female)', 10000),
(UUID(), 'content_creator_of_the_year_female_80', 'JACKIE MATUBIA', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Female)', 10000),
(UUID(), 'content_creator_of_the_year_female_81', 'DIANA BAHATI', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Female)', 10000),
(UUID(), 'content_creator_of_the_year_female_82', 'AZZIAD NASENYA', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Female)', 10000),
(UUID(), 'content_creator_of_the_year_female_83', 'TESS MWAURA', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Female)', 10000),
(UUID(), 'content_creator_of_the_year_female_84', 'MISS TRUDY', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Female)', 10000),
(UUID(), 'content_creator_of_the_year_female_85', 'LYNNE NGUGI', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Female)', 10000),
(UUID(), 'content_creator_of_the_year_female_86', 'MUNGAI EVE', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Female)', 10000),
(UUID(), 'content_creator_of_the_year_female_87', 'DIANA DAISY –GAU', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Female)', 10000),
(UUID(), 'content_creator_of_the_year_female_88', 'MAURINE KABU', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Female)', 10000),
(UUID(), 'content_creator_of_the_year_female_89', 'VELMA ADALA', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Female)', 10000),
(UUID(), 'content_creator_of_the_year_female_90', 'MITCHELLE MJAKA MFINE', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Female)', 10000),
(UUID(), 'content_creator_of_the_year_female_91', 'SHARNIZE ACTRESS', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Female)', 10000),
(UUID(), 'content_creator_of_the_year_female_92', 'JUST SALET', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Female)', 10000),
(UUID(), 'content_creator_of_the_year_female_93', 'ANGEL ATIENO', 'Content Creator of the Year (Female)', '{}', 0, NULL, 'Nominee for Content Creator of the Year (Female)', 10000),
(UUID(), 'entrepreneur_of_the_year_male_94', 'KENJAVA WAKAGOTO', 'Entrepreneur of the Year (Male)', '{}', 0, NULL, 'Nominee for Entrepreneur of the Year (Male)', 10000),
(UUID(), 'entrepreneur_of_the_year_male_95', 'PREZZO LOGISTIC MOULDINGS', 'Entrepreneur of the Year (Male)', '{}', 0, NULL, 'Nominee for Entrepreneur of the Year (Male)', 10000),
(UUID(), 'entrepreneur_of_the_year_male_96', 'MURAGE MODERN PACIFIC FANITURE', 'Entrepreneur of the Year (Male)', '{}', 0, NULL, 'Nominee for Entrepreneur of the Year (Male)', 10000),
(UUID(), 'entrepreneur_of_the_year_male_97', 'MARIDADY MOTORS LTD', 'Entrepreneur of the Year (Male)', '{}', 0, NULL, 'Nominee for Entrepreneur of the Year (Male)', 10000),
(UUID(), 'entrepreneur_of_the_year_male_98', 'MOFARM JM', 'Entrepreneur of the Year (Male)', '{}', 0, NULL, 'Nominee for Entrepreneur of the Year (Male)', 10000),
(UUID(), 'entrepreneur_of_the_year_male_99', 'MWENDA THURANIRA (MAMBO FRESH)', 'Entrepreneur of the Year (Male)', '{}', 0, NULL, 'Nominee for Entrepreneur of the Year (Male)', 10000),
(UUID(), 'entrepreneur_of_the_year_male_100', 'BARUTHI WA THAYU', 'Entrepreneur of the Year (Male)', '{}', 0, NULL, 'Nominee for Entrepreneur of the Year (Male)', 10000),
(UUID(), 'entrepreneur_of_the_year_female_101', 'DAMARIS WA DAMA SPARES', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur of the Year (Female)', 10000),
(UUID(), 'entrepreneur_of_the_year_female_102', 'CATHERINE WAMBUGU (WAMBUGU APPLES)', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur of the Year (Female)', 10000),
(UUID(), 'entrepreneur_of_the_year_female_103', 'SHIKUH HI-STYLE', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur of the Year (Female)', 10000),
(UUID(), 'entrepreneur_of_the_year_female_104', 'BETTY HAMISHA (MUTHONI)', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur of the Year (Female)', 10000),
(UUID(), 'entrepreneur_of_the_year_female_105', 'ESTHER MUCHEMI', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur of the Year (Female)', 10000),
(UUID(), 'entrepreneur_of_the_year_female_106', 'NANA OWITI', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur of the Year (Female)', 10000),
(UUID(), 'entrepreneur_of_the_year_female_107', 'LIZ NJUGUNA', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur of the Year (Female)', 10000),
(UUID(), 'entrepreneur_of_the_year_female_108', 'AMELINA ACHIENG', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur of the Year (Female)', 10000),
(UUID(), 'entrepreneur_of_the_year_female_109', 'ANERLISA MUIGAI', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur of the Year (Female)', 10000),
(UUID(), 'entrepreneur_of_the_year_female_110', 'HILDA MORAA', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur of the Year (Female)', 10000),
(UUID(), 'entrepreneur_of_the_year_female_111', 'NAISIAE NAAADOKILA', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur of the Year (Female)', 10000),
(UUID(), 'entrepreneur_of_the_year_female_112', 'CAROLE KINOTI', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur of the Year (Female)', 10000),
(UUID(), 'entrepreneur_of_the_year_female_113', 'NJERI RIONGE', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur of the Year (Female)', 10000),
(UUID(), 'entrepreneur_of_the_year_female_114', 'WINJOY KANANU', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur of the Year (Female)', 10000),
(UUID(), 'entrepreneur_of_the_year_female_115', 'Hon. ANNASTACIA MUTHINI MUENDOMA', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur of the Year (Female)', 10000),
(UUID(), 'entrepreneur_of_the_year_female_116', 'ESTHER WAKIMANITV NDUKU', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur of the Year (Female)', 10000),
(UUID(), 'entrepreneur_of_the_year_female_117', 'MAURINE KABU', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur of the Year (Female)', 10000),
(UUID(), 'entrepreneur_of_the_year_female_118', 'NANA OWITI', 'Entrepreneur of the Year (Female)', '{}', 0, NULL, 'Nominee for Entrepreneur of the Year (Female)', 10000),
(UUID(), 'youth_leader_of_the_year_male_119', 'HON. BABU OWINO', 'Youth Leader of the Year (Male)', '{}', 0, NULL, 'Nominee for Youth Leader of the Year (Male)', 10000),
(UUID(), 'youth_leader_of_the_year_male_120', 'HON.  JALANGO', 'Youth Leader of the Year (Male)', '{}', 0, NULL, 'Nominee for Youth Leader of the Year (Male)', 10000),
(UUID(), 'youth_leader_of_the_year_male_121', 'HON. NDINDI NYORO', 'Youth Leader of the Year (Male)', '{}', 0, NULL, 'Nominee for Youth Leader of the Year (Male)', 10000),
(UUID(), 'youth_leader_of_the_year_male_122', 'HON. JOHN METHU', 'Youth Leader of the Year (Male)', '{}', 0, NULL, 'Nominee for Youth Leader of the Year (Male)', 10000),
(UUID(), 'youth_leader_of_the_year_male_123', 'HON. JOHN PAUL MWIRIGI', 'Youth Leader of the Year (Male)', '{}', 0, NULL, 'Nominee for Youth Leader of the Year (Male)', 10000),
(UUID(), 'youth_leader_of_the_year_male_124', 'MWANGI MUCHIRI', 'Youth Leader of the Year (Male)', '{}', 0, NULL, 'Nominee for Youth Leader of the Year (Male)', 10000),
(UUID(), 'youth_leader_of_the_year_male_125', 'HON. PETER KALERWA SALASYA', 'Youth Leader of the Year (Male)', '{}', 0, NULL, 'Nominee for Youth Leader of the Year (Male)', 10000),
(UUID(), 'youth_leader_of_the_year_male_126', 'Hon. JALANGO', 'Youth Leader of the Year (Male)', '{}', 0, NULL, 'Nominee for Youth Leader of the Year (Male)', 10000),
(UUID(), 'youth_leader_of_the_year_male_127', 'FIKIRINI JACOBS', 'Youth Leader of the Year (Male)', '{}', 0, NULL, 'Nominee for Youth Leader of the Year (Male)', 10000),
(UUID(), 'youth_leader_of_the_year_male_128', 'STEPHEN LETOO', 'Youth Leader of the Year (Male)', '{}', 0, NULL, 'Nominee for Youth Leader of the Year (Male)', 10000),
(UUID(), 'youth_leader_of_the_year_female_129', 'HON. NJERI MAINA', 'Youth Leader of the Year (Female)', '{}', 0, NULL, 'Nominee for Youth Leader of the Year (Female)', 10000),
(UUID(), 'youth_leader_of_the_year_female_130', 'HON. MBITHE MULINGE', 'Youth Leader of the Year (Female)', '{}', 0, NULL, 'Nominee for Youth Leader of the Year (Female)', 10000),
(UUID(), 'youth_leader_of_the_year_female_131', 'HON. CYNTHIA MUGE', 'Youth Leader of the Year (Female)', '{}', 0, NULL, 'Nominee for Youth Leader of the Year (Female)', 10000),
(UUID(), 'youth_leader_of_the_year_female_132', 'HON. LINET TOTO', 'Youth Leader of the Year (Female)', '{}', 0, NULL, 'Nominee for Youth Leader of the Year (Female)', 10000),
(UUID(), 'youth_leader_of_the_year_female_133', 'HON. ESTHER OKENYURI', 'Youth Leader of the Year (Female)', '{}', 0, NULL, 'Nominee for Youth Leader of the Year (Female)', 10000),
(UUID(), 'youth_leader_of_the_year_female_134', 'KAREN NYAMU', 'Youth Leader of the Year (Female)', '{}', 0, NULL, 'Nominee for Youth Leader of the Year (Female)', 10000),
(UUID(), 'innovator_of_the_year_male_135', 'SIR BONNIE BRANDS', 'Innovator of the Year (Male)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Male)', 10000),
(UUID(), 'innovator_of_the_year_male_136', 'MURAGE MORDERN PACIFIC', 'Innovator of the Year (Male)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Male)', 10000),
(UUID(), 'innovator_of_the_year_male_137', 'BROBOX', 'Innovator of the Year (Male)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Male)', 10000),
(UUID(), 'innovator_of_the_year_male_138', 'MC KAJIM', 'Innovator of the Year (Male)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Male)', 10000),
(UUID(), 'innovator_of_the_year_male_139', 'HAMO THE PROFESSOR', 'Innovator of the Year (Male)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Male)', 10000),
(UUID(), 'innovator_of_the_year_male_140', 'TR_KALAUSI', 'Innovator of the Year (Male)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Male)', 10000),
(UUID(), 'innovator_of_the_year_male_141', 'SIMON PLUMBING', 'Innovator of the Year (Male)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Male)', 10000),
(UUID(), 'innovator_of_the_year_male_142', 'KHOJA AFRIQUE (MUSANII)', 'Innovator of the Year (Male)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Male)', 10000),
(UUID(), 'innovator_of_the_year_male_143', 'DAN WEMA', 'Innovator of the Year (Male)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Male)', 10000),
(UUID(), 'innovator_of_the_year_male_144', 'ELVIS W', 'Innovator of the Year (Male)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Male)', 10000),
(UUID(), 'innovator_of_the_year_male_145', 'KELLY INSPIRATION', 'Innovator of the Year (Male)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Male)', 10000),
(UUID(), 'innovator_of_the_year_male_146', 'PRESENTOR KAI', 'Innovator of the Year (Male)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Male)', 10000),
(UUID(), 'innovator_of_the_year_female_147', 'KELSY KERUBO', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Female)', 10000),
(UUID(), 'innovator_of_the_year_female_148', 'EV MERCY NUNGARI', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Female)', 10000),
(UUID(), 'innovator_of_the_year_female_149', 'MERCY MAINA OFFICIAL', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Female)', 10000),
(UUID(), 'innovator_of_the_year_female_150', 'WANGECI WA KARIUKI', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Female)', 10000),
(UUID(), 'innovator_of_the_year_female_151', 'LUCIANA CREATIVE', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Female)', 10000),
(UUID(), 'innovator_of_the_year_female_152', 'NKATHA OFFICIAL', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Female)', 10000),
(UUID(), 'innovator_of_the_year_female_153', 'ANN GATIBA', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Female)', 10000),
(UUID(), 'innovator_of_the_year_female_154', 'NJERI WA MUIGAI NJOROGE', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Female)', 10000),
(UUID(), 'innovator_of_the_year_female_155', 'WAIRIMU KIMANI', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Female)', 10000),
(UUID(), 'innovator_of_the_year_female_156', 'NAISIAE NAADOKILA', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Female)', 10000),
(UUID(), 'innovator_of_the_year_female_157', 'TRISHA KHALID', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Female)', 10000),
(UUID(), 'innovator_of_the_year_female_158', 'CHELAA VALLEYGIRL', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Female)', 10000),
(UUID(), 'innovator_of_the_year_female_159', 'BETTY BAYO', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Female)', 10000),
(UUID(), 'innovator_of_the_year_female_160', 'STACY WA DIGITAL', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Female)', 10000),
(UUID(), 'innovator_of_the_year_female_161', 'CAROL KATRUE', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Female)', 10000),
(UUID(), 'innovator_of_the_year_female_162', 'MAURINE KABU', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Female)', 10000),
(UUID(), 'innovator_of_the_year_female_163', 'DIANA YEGON', 'Innovator of the Year (Female)', '{}', 0, NULL, 'Nominee for Innovator of the Year (Female)', 10000),
(UUID(), 'comedian_of_the_year_male_164', 'MC-GOGO', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian of the year (male)', 10000),
(UUID(), 'comedian_of_the_year_male_165', 'SENGE HELLENA', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian of the year (male)', 10000),
(UUID(), 'comedian_of_the_year_male_166', 'GOGO SMALL', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian of the year (male)', 10000),
(UUID(), 'comedian_of_the_year_male_167', 'SAMMY KIOKO COMEDIAN', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian of the year (male)', 10000),
(UUID(), 'comedian_of_the_year_male_168', 'JAYMO DECIN', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian of the year (male)', 10000),
(UUID(), 'comedian_of_the_year_male_169', 'MOJEJE KIAZALA', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian of the year (male)', 10000),
(UUID(), 'comedian_of_the_year_male_170', 'KAFENGO', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian of the year (male)', 10000),
(UUID(), 'comedian_of_the_year_male_171', 'WILSON MACHARIA', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian of the year (male)', 10000),
(UUID(), 'comedian_of_the_year_male_172', 'NGANO COMEDIAN', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian of the year (male)', 10000),
(UUID(), 'comedian_of_the_year_male_173', 'NYONJORO', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian of the year (male)', 10000),
(UUID(), 'comedian_of_the_year_male_174', 'MURIFE', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian of the year (male)', 10000),
(UUID(), 'comedian_of_the_year_male_175', 'FLAQO', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian of the year (male)', 10000),
(UUID(), 'comedian_of_the_year_male_176', 'GIKONYORE', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian of the year (male)', 10000),
(UUID(), 'comedian_of_the_year_male_177', 'VINNIE BAITE', 'Comedian of the year (male)', '{}', 0, NULL, 'Nominee for Comedian of the year (male)', 10000),
(UUID(), 'comedian_of_the_year_female_178', 'NASRA', 'Comedian of the year (female)', '{}', 0, NULL, 'Nominee for Comedian of the year (female)', 10000),
(UUID(), 'comedian_of_the_year_female_179', 'JEMUTAI', 'Comedian of the year (female)', '{}', 0, NULL, 'Nominee for Comedian of the year (female)', 10000),
(UUID(), 'comedian_of_the_year_female_180', 'WANJIRU CLAIRE FUNS', 'Comedian of the year (female)', '{}', 0, NULL, 'Nominee for Comedian of the year (female)', 10000),
(UUID(), 'comedian_of_the_year_female_181', 'MAMITO EUNICE', 'Comedian of the year (female)', '{}', 0, NULL, 'Nominee for Comedian of the year (female)', 10000),
(UUID(), 'comedian_of_the_year_female_182', 'WAJOY', 'Comedian of the year (female)', '{}', 0, NULL, 'Nominee for Comedian of the year (female)', 10000),
(UUID(), 'comedian_of_the_year_female_183', 'AUNTIE JEMIMAH', 'Comedian of the year (female)', '{}', 0, NULL, 'Nominee for Comedian of the year (female)', 10000),
(UUID(), 'community_champion_of_the_year_male_184', 'GEOFFREY MOSIRIA', 'Community Champion of the Year (Male)', '{}', 0, NULL, 'Nominee for Community Champion of the Year (Male)', 10000),
(UUID(), 'community_champion_of_the_year_male_185', 'FATHER KINYUA’S ONLINE', 'Community Champion of the Year (Male)', '{}', 0, NULL, 'Nominee for Community Champion of the Year (Male)', 10000),
(UUID(), 'community_champion_of_the_year_male_186', 'SAMMY ONDIMU NGARE', 'Community Champion of the Year (Male)', '{}', 0, NULL, 'Nominee for Community Champion of the Year (Male)', 10000),
(UUID(), 'community_champion_of_the_year_male_187', 'MORARA KEBASO', 'Community Champion of the Year (Male)', '{}', 0, NULL, 'Nominee for Community Champion of the Year (Male)', 10000),
(UUID(), 'community_champion_of_the_year_male_188', 'KURURIA TV', 'Community Champion of the Year (Male)', '{}', 0, NULL, 'Nominee for Community Champion of the Year (Male)', 10000),
(UUID(), 'community_champion_of_the_year_male_189', 'ELVIS W', 'Community Champion of the Year (Male)', '{}', 0, NULL, 'Nominee for Community Champion of the Year (Male)', 10000),
(UUID(), 'community_champion_of_the_year_female_190', 'SHIKSHA ARORA', 'Community Champion of the Year (Female)', '{}', 0, NULL, 'Nominee for Community Champion of the Year (Female)', 10000),
(UUID(), 'community_champion_of_the_year_female_191', 'WANJA NYARARI ROSE', 'Community Champion of the Year (Female)', '{}', 0, NULL, 'Nominee for Community Champion of the Year (Female)', 10000),
(UUID(), 'community_champion_of_the_year_female_192', 'REV. JOY BENSON', 'Community Champion of the Year (Female)', '{}', 0, NULL, 'Nominee for Community Champion of the Year (Female)', 10000),
(UUID(), 'community_champion_of_the_year_female_193', 'Tr. CILLAH', 'Community Champion of the Year (Female)', '{}', 0, NULL, 'Nominee for Community Champion of the Year (Female)', 10000),
(UUID(), 'community_champion_of_the_year_female_194', 'WANJIKU STEPHENS', 'Community Champion of the Year (Female)', '{}', 0, NULL, 'Nominee for Community Champion of the Year (Female)', 10000),
(UUID(), 'community_champion_of_the_year_female_195', 'TEACHER MARION MUKENYI', 'Community Champion of the Year (Female)', '{}', 0, NULL, 'Nominee for Community Champion of the Year (Female)', 10000),
(UUID(), 'community_champion_of_the_year_female_196', 'HON. SHARLEEN WAMBUI MAINA (SHAR)', 'Community Champion of the Year (Female)', '{}', 0, NULL, 'Nominee for Community Champion of the Year (Female)', 10000),
(UUID(), 'community_champion_of_the_year_female_197', 'KARIGITHINJI', 'Community Champion of the Year (Female)', '{}', 0, NULL, 'Nominee for Community Champion of the Year (Female)', 10000),
(UUID(), 'community_champion_of_the_year_female_198', 'REHEMA KITETO', 'Community Champion of the Year (Female)', '{}', 0, NULL, 'Nominee for Community Champion of the Year (Female)', 10000),
(UUID(), 'community_champion_of_the_year_female_199', 'DIANA DAISY –GAU', 'Community Champion of the Year (Female)', '{}', 0, NULL, 'Nominee for Community Champion of the Year (Female)', 10000),
(UUID(), 'community_champion_of_the_year_female_200', 'LYNN NGUGI', 'Community Champion of the Year (Female)', '{}', 0, NULL, 'Nominee for Community Champion of the Year (Female)', 10000),
(UUID(), 'influencer_of_the_year_male_201', 'BABA TALISHA', 'Influencer of the Year (Male)', '{}', 0, NULL, 'Nominee for Influencer of the Year (Male)', 10000),
(UUID(), 'influencer_of_the_year_male_202', 'Dr. OFWENEKE', 'Influencer of the Year (Male)', '{}', 0, NULL, 'Nominee for Influencer of the Year (Male)', 10000),
(UUID(), 'influencer_of_the_year_male_203', 'OGA OBINNA', 'Influencer of the Year (Male)', '{}', 0, NULL, 'Nominee for Influencer of the Year (Male)', 10000),
(UUID(), 'influencer_of_the_year_male_204', 'Tom DAKTARI', 'Influencer of the Year (Male)', '{}', 0, NULL, 'Nominee for Influencer of the Year (Male)', 10000),
(UUID(), 'influencer_of_the_year_male_205', 'HAMO THE PROFFESOR', 'Influencer of the Year (Male)', '{}', 0, NULL, 'Nominee for Influencer of the Year (Male)', 10000),
(UUID(), 'influencer_of_the_year_female_206', 'SANDRA DACHA', 'Influencer of the Year (Female)', '{}', 0, NULL, 'Nominee for Influencer of the Year (Female)', 10000),
(UUID(), 'influencer_of_the_year_female_207', 'WANJA MWAURA', 'Influencer of the Year (Female)', '{}', 0, NULL, 'Nominee for Influencer of the Year (Female)', 10000),
(UUID(), 'influencer_of_the_year_female_208', 'TRIZA MAMAKE MURAYA', 'Influencer of the Year (Female)', '{}', 0, NULL, 'Nominee for Influencer of the Year (Female)', 10000),
(UUID(), 'influencer_of_the_year_female_209', 'Lulu Hassan', 'Influencer of the Year (Female)', '{}', 0, NULL, 'Nominee for Influencer of the Year (Female)', 10000),
(UUID(), 'influencer_of_the_year_female_210', 'Dr. Regina King’ori CPA-K', 'Influencer of the Year (Female)', '{}', 0, NULL, 'Nominee for Influencer of the Year (Female)', 10000),
(UUID(), 'influencer_of_the_year_female_211', 'NAOMI KURIA', 'Influencer of the Year (Female)', '{}', 0, NULL, 'Nominee for Influencer of the Year (Female)', 10000),
(UUID(), 'influencer_of_the_year_female_212', 'ECRENE MADAGA', 'Influencer of the Year (Female)', '{}', 0, NULL, 'Nominee for Influencer of the Year (Female)', 10000),
(UUID(), 'influencer_of_the_year_female_213', 'MILLY CHEBBY', 'Influencer of the Year (Female)', '{}', 0, NULL, 'Nominee for Influencer of the Year (Female)', 10000),
(UUID(), 'dj_of_the_year_male_214', 'DJMOKENYA', 'DJ of the year (Male)', '{}', 0, NULL, 'Nominee for DJ of the year (Male)', 10000),
(UUID(), 'dj_of_the_year_male_215', 'DJ MACDEE TOP MC', 'DJ of the year (Male)', '{}', 0, NULL, 'Nominee for DJ of the year (Male)', 10000),
(UUID(), 'dj_of_the_year_male_216', 'DJ DIBUL', 'DJ of the year (Male)', '{}', 0, NULL, 'Nominee for DJ of the year (Male)', 10000),
(UUID(), 'dj_of_the_year_female_217', 'DJ SOFIA MACHARIA', 'DJ of the Year (Female)', '{}', 0, NULL, 'Nominee for DJ of the Year (Female)', 10000),
(UUID(), 'dj_of_the_year_female_218', 'DJ NYC KENYA', 'DJ of the Year (Female)', '{}', 0, NULL, 'Nominee for DJ of the Year (Female)', 10000),
(UUID(), 'dj_of_the_year_female_219', 'DJ SONNIE M', 'DJ of the Year (Female)', '{}', 0, NULL, 'Nominee for DJ of the Year (Female)', 10000),
(UUID(), 'dj_of_the_year_female_220', 'DJ SLIM 254', 'DJ of the Year (Female)', '{}', 0, NULL, 'Nominee for DJ of the Year (Female)', 10000),
(UUID(), 'podcast_of_the_year_221', 'MC KOGI INVESTOR', 'PODCAST OF THE YEAR', '{}', 0, NULL, 'Nominee for PODCAST OF THE YEAR', 10000),
(UUID(), 'podcast_of_the_year_222', 'GUKA WA NYUMBA KUMI', 'PODCAST OF THE YEAR', '{}', 0, NULL, 'Nominee for PODCAST OF THE YEAR', 10000),
(UUID(), 'podcast_of_the_year_223', 'JEFF KURIA', 'PODCAST OF THE YEAR', '{}', 0, NULL, 'Nominee for PODCAST OF THE YEAR', 10000),
(UUID(), 'podcast_of_the_year_224', 'PAXSON CHEGE NGUNYA', 'PODCAST OF THE YEAR', '{}', 0, NULL, 'Nominee for PODCAST OF THE YEAR', 10000),
(UUID(), 'podcast_of_the_year_225', 'LYNNE NGUGI', 'PODCAST OF THE YEAR', '{}', 0, NULL, 'Nominee for PODCAST OF THE YEAR', 10000),
(UUID(), 'podcast_of_the_year_226', 'MIC CHEQUE', 'PODCAST OF THE YEAR', '{}', 0, NULL, 'Nominee for PODCAST OF THE YEAR', 10000),
(UUID(), 'podcast_of_the_year_227', 'THE MESSY IN BETWEEN', 'PODCAST OF THE YEAR', '{}', 0, NULL, 'Nominee for PODCAST OF THE YEAR', 10000),
(UUID(), 'podcast_of_the_year_228', 'BY THE WAY', 'PODCAST OF THE YEAR', '{}', 0, NULL, 'Nominee for PODCAST OF THE YEAR', 10000),
(UUID(), 'facebook_pages_of_the_year_229', 'SIKIKA ROAD SAFETY', 'Facebook pages of the year', '{}', 0, NULL, 'Nominee for Facebook pages of the year', 10000),
(UUID(), 'facebook_pages_of_the_year_230', 'TUKO.CO.KE', 'Facebook pages of the year', '{}', 0, NULL, 'Nominee for Facebook pages of the year', 10000),
(UUID(), 'facebook_pages_of_the_year_231', 'KENYANS.CO.KE', 'Facebook pages of the year', '{}', 0, NULL, 'Nominee for Facebook pages of the year', 10000),
(UUID(), 'facebook_pages_of_the_year_232', 'MWAGO WA MUGIKUYU', 'Facebook pages of the year', '{}', 0, NULL, 'Nominee for Facebook pages of the year', 10000),
(UUID(), 'facebook_pages_of_the_year_233', 'DMK MEDIA GROUP', 'Facebook pages of the year', '{}', 0, NULL, 'Nominee for Facebook pages of the year', 10000),
(UUID(), 'facebook_pages_of_the_year_234', '7 NEWS GLOBAL', 'Facebook pages of the year', '{}', 0, NULL, 'Nominee for Facebook pages of the year', 10000),
(UUID(), 'facebook_pages_of_the_year_235', 'NAIROBI GOSSIP CLUB', 'Facebook pages of the year', '{}', 0, NULL, 'Nominee for Facebook pages of the year', 10000),
(UUID(), 'facebook_pages_of_the_year_236', 'PULSE KENYA', 'Facebook pages of the year', '{}', 0, NULL, 'Nominee for Facebook pages of the year', 10000),
(UUID(), 'facebook_pages_of_the_year_237', 'MALEMA TV', 'Facebook pages of the year', '{}', 0, NULL, 'Nominee for Facebook pages of the year', 10000);