INSERT INTO nominees (code, id, name, category, metadata, votes, created_at, updated_at, image, description, vote_target, gender) VALUES
(NULL, NULL, 'SENGE HELLENA', 'Comedian of the year (male)', '{}', 0, NOW(), NOW(), NULL, 'For a male comedian who is creative, entertaining and informative', 10000, 'male'),
(NULL, NULL, 'JAYMOH DECIN (BORN FUNNY)', 'Content Creator of the Year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For a male content creator producing creative, entertaining, and impactful videos or posts.', 10000, 'male'),
(NULL, NULL, 'NYEVU FONDO', 'Content Creator of the Year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For a male content creator producing creative, entertaining, and impactful videos or posts.', 10000, 'male'),
(NULL, NULL, 'MIKEWAKO', 'Content Creator of the Year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For a male content creator producing creative, entertaining, and impactful videos or posts.', 10000, 'male'),
(NULL, NULL, 'KUSHYDAY', 'Content Creator of the Year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For a male content creator producing creative, entertaining, and impactful videos or posts.', 10000, 'male'),
(NULL, NULL, 'ATIENO OTIENO', 'Content Creator of the Year (Female)', '{}', 0, NOW(), NOW(), NULL, 'For a female content creator producing creative, entertaining, and impactful videos or posts.', 10000, 'female'),
(NULL, NULL, 'LUPITA NYAKISUMU', 'Content Creator of the Year (Female)', '{}', 0, NOW(), NOW(), NULL, 'For a female content creator producing creative, entertaining, and impactful videos or posts.', 10000, 'female'),
(NULL, NULL, 'NKATHA OFFICIAL', 'Content Creator of the Year (Female)', '{}', 0, NOW(), NOW(), NULL, 'For a female content creator producing creative, entertaining, and impactful videos or posts.', 10000, 'female'),
(NULL, NULL, 'ROSY MAMAKE WAITHERERO', 'Content Creator of the Year (Female)', '{}', 0, NOW(), NOW(), NULL, 'For a female content creator producing creative, entertaining, and impactful videos or posts.', 10000, 'female'),
(NULL, NULL, 'HARRIET NJENGA', 'Content Creator of the Year (Female)', '{}', 0, NOW(), NOW(), NULL, 'For a female content creator producing creative, entertaining, and impactful videos or posts.', 10000, 'female'),
(NULL, NULL, 'BRAYO WA NDARUGO MAWE', 'Entrepreneur of the Year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For a man demonstrating exceptional business innovation, growth, and leadership.', 10000, 'male'),
(NULL, NULL, 'KEN THE FARMER', 'Entrepreneur of the Year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For a man demonstrating exceptional business innovation, growth, and leadership.', 10000, 'male'),
(NULL, NULL, 'BRAY OKUT', 'Entrepreneur of the Year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For a man demonstrating exceptional business innovation, growth, and leadership.', 10000, 'male'),
(NULL, NULL, 'THEE PLUTO', 'Entrepreneur of the Year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For a man demonstrating exceptional business innovation, growth, and leadership.', 10000, 'male'),
(NULL, NULL, 'KHALIF KAIRO', 'Entrepreneur of the Year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For a man demonstrating exceptional business innovation, growth, and leadership.', 10000, 'male'),
(NULL, NULL, 'ESSY KILINDI (ESSY SMART PRINTERS)', 'Entrepreneur of the Year (Female)', '{}', 0, NOW(), NOW(), NULL, 'For a woman demonstrating exceptional business innovation, growth, and leadership.', 10000, 'female'),
(NULL, NULL, 'NORAH MUENDO (NILA BABY SHOP)', 'Entrepreneur of the Year (Female)', '{}', 0, NOW(), NOW(), NULL, 'For a woman demonstrating exceptional business innovation, growth, and leadership.', 10000, 'female'),
(NULL, NULL, 'KENDI MUTHOMI MSC', 'Entrepreneur of the Year (Female)', '{}', 0, NOW(), NOW(), NULL, 'For a woman demonstrating exceptional business innovation, growth, and leadership.', 10000, 'female'),
(NULL, NULL, 'HON. ALLAN CHESANG', 'Youth Leader of the Year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For a young male leader representing youth voices and driving positive change.', 10000, 'male'),
(NULL, NULL, 'HON.SYOMBUA KIOKO', 'Youth Leader of the Year (Female)', '{}', 0, NOW(), NOW(), NULL, 'For a young female leader representing youth voices and driving positive change.', 10000, 'female'),
(NULL, NULL, 'PRESENTER KAI', 'Innovator of the Year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For a man introducing impactful ideas, products, or services changing lives.', 10000, 'male'),
(NULL, NULL, 'PROPHETES MONICAH', 'Innovator of the Year (Female)', '{}', 0, NOW(), NOW(), NULL, 'For a woman introducing impactful ideas, products, or services changing lives.', 10000, 'female'),
(NULL, NULL, 'UJINGA ZA VICTOR NOMAM', 'Comedian of the year (male)', '{}', 0, NOW(), NOW(), NULL, 'For a male comedian who is creative, entertaining and informative', 10000, 'male'),
(NULL, NULL, 'AKUKU DANGER THE COMEDIAN', 'Comedian of the year (male)', '{}', 0, NOW(), NOW(), NULL, 'For a male comedian who is creative, entertaining and informative', 10000, 'male'),
(NULL, NULL, 'GK SERKAL', 'Comedian of the year (male)', '{}', 0, NOW(), NOW(), NULL, 'For a male comedian who is creative, entertaining and informative', 10000, 'male'),
(NULL, NULL, 'SHIRO KAREITHI', 'Comedian of the year (female)', '{}', 0, NOW(), NOW(), NULL, 'For a female comedian who is creative, entertaining and informative', 10000, 'female'),
(NULL, NULL, 'PRETTY SHAN', 'Comedian of the year (female)', '{}', 0, NOW(), NOW(), NULL, 'For a female comedian who is creative, entertaining and informative', 10000, 'female'),
(NULL, NULL, 'SANDRA DACHA', 'Comedian of the year (female)', '{}', 0, NOW(), NOW(), NULL, 'For a female comedian who is creative, entertaining and informative', 10000, 'female'),
(NULL, NULL, 'LENCER NYASUBA', 'Comedian of the year (female)', '{}', 0, NOW(), NOW(), NULL, 'For a female comedian who is creative, entertaining and informative', 10000, 'female'),
(NULL, NULL, 'JOSEE JOE', 'Community Champion of the Year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For a man making a significant grassroots impact without seeking fame.', 10000, 'male'),
(NULL, NULL, 'MWALIMU RACHEL', 'Community Champion of the Year (Female)', '{}', 0, NOW(), NOW(), NULL, 'For a woman making a significant grassroots impact without seeking fame.', 10000, 'female'),
(NULL, NULL, 'WANJIKU -- HUTIA MUNDU', 'Community Champion of the Year (Female)', '{}', 0, NOW(), NOW(), NULL, 'For a woman making a significant grassroots impact without seeking fame.', 10000, 'female'),
(NULL, NULL, 'NICHOLAS KIOKO', 'Influencer of the Year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For a man whose online presence shaped conversations positively?', 10000, 'male'),
(NULL, NULL, 'CAREY_ PRISCILA', 'Influencer of the Year (Female)', '{}', 0, NOW(), NOW(), NULL, 'For a woman whose online presence shaped conversations positively?', 10000, 'female'),
(NULL, NULL, 'DOLLY FAMILY', 'Influencer of the Year (Female)', '{}', 0, NOW(), NOW(), NULL, 'For a woman whose online presence shaped conversations positively?', 10000, 'female'),
(NULL, NULL, 'MUMMIE FRANCIE', 'Influencer of the Year (Female)', '{}', 0, NOW(), NOW(), NULL, 'For a woman whose online presence shaped conversations positively?', 10000, 'female'),
(NULL, NULL, 'FABBY KARAN', 'Influencer of the Year (Female)', '{}', 0, NOW(), NOW(), NULL, 'For a woman whose online presence shaped conversations positively?', 10000, 'female'),
(NULL, NULL, 'DE COOLKID', 'Influencer of the Year (Female)', '{}', 0, NOW(), NOW(), NULL, 'For a woman whose online presence shaped conversations positively?', 10000, 'female'),
(NULL, NULL, 'RAWDER KIDULA KEDAHA', 'Influencer of the Year (Female)', '{}', 0, NOW(), NOW(), NULL, 'For a woman whose online presence shaped conversations positively?', 10000, 'female'),
(NULL, NULL, 'DJSADIC', 'DJ of the year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For male DJ who continuously engage, entertain and maintain standard on the desk.', 10000, 'male'),
(NULL, NULL, 'DJ NOSH254', 'DJ of the year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For male DJ who continuously engage, entertain and maintain standard on the desk.', 10000, 'male'),
(NULL, NULL, 'DJ KYM NICKDEE', 'DJ of the year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For male DJ who continuously engage, entertain and maintain standard on the desk.', 10000, 'male'),
(NULL, NULL, 'DJ JOE MFALME', 'DJ of the year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For male DJ who continuously engage, entertain and maintain standard on the desk.', 10000, 'male'),
(NULL, NULL, 'DJ SISSE', 'DJ of the year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For male DJ who continuously engage, entertain and maintain standard on the desk.', 10000, 'male'),
(NULL, NULL, 'DJ DAFFY', 'DJ of the year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For male DJ who continuously engage, entertain and maintain standard on the desk.', 10000, 'male'),
(NULL, NULL, 'DJ DARLINGTON', 'DJ of the year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For male DJ who continuously engage, entertain and maintain standard on the desk.', 10000, 'male'),
(NULL, NULL, 'EPIC THE DJ', 'DJ of the year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For male DJ who continuously engage, entertain and maintain standard on the desk.', 10000, 'male'),
(NULL, NULL, 'DJ TIBZ', 'DJ of the year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For male DJ who continuously engage, entertain and maintain standard on the desk.', 10000, 'male'),
(NULL, NULL, 'DJ GEE GEE', 'DJ of the year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For male DJ who continuously engage, entertain and maintain standard on the desk.', 10000, 'male'),
(NULL, NULL, 'DJ LEBBZ', 'DJ of the year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For male DJ who continuously engage, entertain and maintain standard on the desk.', 10000, 'male'),
(NULL, NULL, 'DJ SULE', 'DJ of the year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For male DJ who continuously engage, entertain and maintain standard on the desk.', 10000, 'male'),
(NULL, NULL, 'DJ ZEDDY', 'DJ of the year (Male)', '{}', 0, NOW(), NOW(), NULL, 'For male DJ who continuously engage, entertain and maintain standard on the desk.', 10000, 'male'),
(NULL, NULL, 'DJ LISNEY', 'DJ of the Year (Female)', '{}', 0, NOW(), NOW(), NULL, 'For female DJ who continuously engage, entertain and maintain standard on the desk.', 10000, 'female'),
(NULL, NULL, 'DJ BECKY', 'DJ of the Year (Female)', '{}', 0, NOW(), NOW(), NULL, 'For female DJ who continuously engage, entertain and maintain standard on the desk.', 10000, 'female'),
(NULL, NULL, 'DJ NASTIAH', 'DJ of the Year (Female)', '{}', 0, NOW(), NOW(), NULL, 'For female DJ who continuously engage, entertain and maintain standard on the desk.', 10000, 'female'),
(NULL, NULL, 'DJ MALAIKA', 'DJ of the Year (Female)', '{}', 0, NOW(), NOW(), NULL, 'For female DJ who continuously engage, entertain and maintain standard on the desk.', 10000, 'female'),
(NULL, NULL, 'DJ BUNNEY254', 'DJ of the Year (Female)', '{}', 0, NOW(), NOW(), NULL, 'For female DJ who continuously engage, entertain and maintain standard on the desk.', 10000, 'female'),
(NULL, NULL, 'DJ PIERRA MAKENA', 'DJ of the Year (Female)', '{}', 0, NOW(), NOW(), NULL, 'For female DJ who continuously engage, entertain and maintain standard on the desk.', 10000, 'female'),
(NULL, NULL, 'RICK BE TV', 'PODCAST OF THE YEAR', '{}', 0, NOW(), NOW(), NULL, 'Podcast of the year', 10000, NULL),
(NULL, NULL, 'THE REPORTER KE', 'Facebook pages of the year', '{}', 0, NOW(), NOW(), NULL, 'For a Facebook page that is impactful, authentic and informative', 10000, NULL),
(NULL, NULL, 'HABARI AFRICA TV', 'Facebook pages of the year', '{}', 0, NOW(), NOW(), NULL, 'For a Facebook page that is impactful, authentic and informative', 10000, NULL),
(NULL, NULL, 'THIKA TOWN TODAY -- 3T', 'Facebook pages of the year', '{}', 0, NOW(), NOW(), NULL, 'For a Facebook page that is impactful, authentic and informative', 10000, NULL),
(NULL, NULL, 'JAYMOHDECIN (CHOKE JINGLI)', 'TIKTOKER of the year male', '{}', 0, NOW(), NOW(), NULL, 'Awarded to the most outstanding male TikTok creator who has shown excellence in content creation and influence.', 10000, 'male'),
(NULL, NULL, 'MANZI WA MOMBASA', 'TIKTOKER of the year female', '{}', 0, NOW(), NOW(), NULL, 'Awarded to the most outstanding female TikTok creator who has shown excellence in content creation and influence.', 10000, 'female'),
(NULL, NULL, 'MC JAPHE', 'MC male category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'MC SIR ROBBIH KENYA (CEO UUZAH EVENTS)', 'MC male category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'MC GOGO', 'MC male category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'MC GITOERO', 'MC male category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'MC TOTO', 'MC male category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'MC JIMMY KAJIM', 'MC male category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'MC NZOMO MWEENE', 'MC male category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'MC MITCH KENYA', 'MC male category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'WAITHA WA JANE', 'Artist Male category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'SAMIDOH', 'Artist Male category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'TONY YOUNG', 'Artist Male category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'JACKSON MUTINDA MASEKETE', 'Artist Male category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'MAXWELL MWALIMU', 'Artist Male category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'ARROW BOY', 'Artist Male category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'WILLY PAUL', 'Artist Male category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'KRG THE DON', 'Artist Male category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'IYANII', 'Artist Male category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'VIJANA BARUBARU', 'Artist Male category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'PRINCE INDAH', 'Artist Male category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'QARE THE MASK', 'Artist Male category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'BENSOUL', 'Artist Male category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'GURDIAN ANGEL', 'Artist Male category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'TRIO MIO', 'Artist Male category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'CHARISMA', 'Artist Male category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'OKELLO MAX', 'Artist Male category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'Vicky Brilliance', 'Artist Female Category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'female'),
(NULL, NULL, 'NADIA MUKAMI', 'Artist Female Category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'female'),
(NULL, NULL, 'SSARU', 'Artist Female Category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'female'),
(NULL, NULL, 'TESLA', 'Artist Female Category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'female'),
(NULL, NULL, 'SANAIPEI TANDE', 'Artist Female Category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'female'),
(NULL, NULL, 'FEMI ONE', 'Artist Female Category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'female'),
(NULL, NULL, 'BRANDY MAINA', 'Artist Female Category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'female'),
(NULL, NULL, 'AVRIL', 'Artist Female Category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'female'),
(NULL, NULL, 'DIANA MARUA', 'Artist Female Category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'female'),
(NULL, NULL, 'SOFIYA NZAU', 'Artist Female Category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'female'),
(NULL, NULL, 'JOVIAL', 'Artist Female Category', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'female'),
(NULL, NULL, 'DIRECTOR CLAMSY', 'PHOTOGRAPHER MALE CATEGORY', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'KAPEDO', 'PHOTOGRAPHER MALE CATEGORY', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'MUTEMWA', 'PHOTOGRAPHER MALE CATEGORY', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'REACE PHOTOGRAPHY', 'PHOTOGRAPHER MALE CATEGORY', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'SAMTINDA', 'PHOTOGRAPHER MALE CATEGORY', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'SIR TONY', 'PHOTOGRAPHER MALE CATEGORY', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'SOBUKWE NONKWE', 'PHOTOGRAPHER MALE CATEGORY', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'MBARUK MWALIMU RADIO 47', 'MEDIA PERSONALITY MALE', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'ALEX MWAKIDEU RADIO 47', 'MEDIA PERSONALITY MALE', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'CLEMMO RADIO MAISHA', 'MEDIA PERSONALITY MALE', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'MZAZI WILLY M TUVA RADIO CITIZEN', 'MEDIA PERSONALITY MALE', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'JEFF KOINANGE HOT 96', 'MEDIA PERSONALITY MALE', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'RASHID ABDALLA CITIZEN TV', 'MEDIA PERSONALITY MALE', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'MAINA KAGENI CLASSIC 105', 'MEDIA PERSONALITY MALE', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'MANUCHO MANUCHO RADIO 47', 'MEDIA PERSONALITY MALE', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'SHUGA BOY RADIO MAISHA', 'MEDIA PERSONALITY MALE', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'TONY MWIRIGI MILELE FM', 'MEDIA PERSONALITY MALE', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male'),
(NULL, NULL, 'AZEEZAH HASHIM HOT 96', 'MEDIA PERSONALITY FEMALE', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'female'),
(NULL, NULL, 'SELLY KADOT RADIO CITIZEN', 'MEDIA PERSONALITY FEMALE', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'female'),
(NULL, NULL, 'CYNTHIA MWANGI HOT 96', 'MEDIA PERSONALITY FEMALE', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'female'),
(NULL, NULL, 'JITABI SULEIMAN RADIO MAISHA', 'MEDIA PERSONALITY FEMALE', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'female'),
(NULL, NULL, 'EVAH MWALILI RADIO 47', 'MEDIA PERSONALITY FEMALE', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'female'),
(NULL, NULL, 'MASSAWE JAPANNI RADIO JAMBO', 'MEDIA PERSONALITY FEMALE', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'female'),
(NULL, NULL, 'MWALIMU RACHEL KISS 100', 'MEDIA PERSONALITY FEMALE', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'female'),
(NULL, NULL, 'KALONDU MUSYIMI MPASHO', 'MEDIA PERSONALITY FEMALE', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'female'),
(NULL, NULL, 'CLAUDIA NAISABWA NATION FM', 'MEDIA PERSONALITY FEMALE', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'female'),
(NULL, NULL, 'CAREN KIBBETT KBC CHANNEL ONE', 'MEDIA PERSONALITY FEMALE', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'female'),
(NULL, NULL, 'SIMON PLUMBING', 'SKILLED EXPERTS MALE', '{}', 0, NOW(), NOW(), NULL, NULL, 10000, 'male');